### ISSUE TITLE
got a error when run run.sh

### ISSUE THREAD

**Issue by elohffa** [mu373/umbrel-docker#1]
/entrypoint.sh: line 6: /home/xxx/data/umbrel-docker/data/scripts/start: Permission denied

When I run bash run.sh . it said above error message. I already grant the premission on the data folder in 777

Thanks

**Comment by mu373** [comment]
Sorry, I do not provide support for this repository as it is just for personal and testing purpose.

With that being said, `docker compose up -d` works without any errors in my environment. Normally, you do not need to run shell scripts (including `run.sh`) manually by yourself, because everything is ran automatically by Docker.

Please also check the [original repository](https://gitlab.com/shrugal/umbrel-docker/-/tree/main/) that I forked for details of `run.sh` script.
